@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members

class Main {
    +{static} main(args: String[*])
}

package jeu {
    package logic {
        class GestionPartie {
            - m_numPartie : Integer
            - m_victoireJ : Integer
            - m_victoireE : Integer
            - m_numTour : Integer
            - m_j : Joueur
            - m_adv : Adversaire
            - m_affichage : AffichageConsole
            - m_combat : Combat
            - m_action : String
            - m_score : Score
            - piocherTour = true : Boolean
            - m_messageAlerteCOurant = " " : String
            + <<create>> GestionPartie()
            + lancerJeu() : Boolean
            + preparerNouvelleManche()
            + verifMort(adv : Adversaire, jou : Joueur)
            + debutTour() : Boolean
            + demanderActionJoueur()
            + boucleTour() : Boolean
            + finTour()
            + rafraichirEcran()
            + sacrifice() : Boolean
            + placerCarte() : Boolean
            + gererPierreSacrifice()
            + verifFinManche() : Boolean
            + finManche() : Boolean
            + finPartie() : Boolean
            + verifFinPartie() : Boolean
        }
        class Score {
            - m_balanceScore : Integer
            + <<create>> Score()
            + ajouterPointsJoueur(points : Integer)
            + ajouterPointsEnnemi(points : Integer)
            + getValeurEcart() : Integer
            + estVictoireJoueur() : Boolean
            + estVictoireEnnemi() : Boolean
            + getScoreJoueur() : String
            + getScoreEnnemi() : String
            + setvaleurJoueur(nouvelleValeur : Integer)
            + setValeurEnnemi(nouvelleValeur : Integer)
        }
        class Combat {
            + gererAttaqueFinTour(joueur : Joueur, adversaire : Adversaire, score : Score)
            - executerAttaque(attaquant : Carte, cible : Carte, position : Integer, estEnnemi : boolean, resume : StringBuilder, score : Score) : Integer
            + appliquerDegats(attaquant : Animal, cible : Carte) : Integer
        }
        class Joueur {
            - m_cartesEnMain : ArrayList<Animal>
            - m_ligneJ : ArrayList<Carte>
            - m_pioche : ArrayList<Animal>
            - nbOsDisponibles : Integer
            - nbSangDisponibles : Integer
            - isNull : boolean
            - m_nbCartePioche = 0 : Integer
            - m_pouvoir : ArrayList<Pouvoir>
            - m_pouvoirADonner : ArrayList<Pouvoir>
            + <<create>> Joueur()
            + getNbOsDisponibles() : Integer
            + ajouterOs(quantite : Integer)
            + consommerOs(quantite : Integer)
            + ajouterSang(quantite : Integer)
            + consommerSang(quantite : Integer)
            + initialiserPiocheDeBase()
            + piocher() : Animal
            + ajoutercartes(carte : Animal)
            + ajouterCartesMain(carte : Animal)
            + getNombreCartes() : Integer
            + addPvr(p : Pouvoir) : Boolean
            + setSangJoueur(i : Integer)
            + setNbOsDisponibles(i : Integer)
            + incrSang()
            + tuer(index : Integer)
            + getPvrType(index : Integer)
            + ajoutermain(carte : Animal, index : Integer)
            + changerSlot(c : Carte, pos : Integer) : String
            + placerCarteJoueur(c : Carte, pos : Integer) : Boolean
            + enleverCarteJoueurPlateau(index : Integer) : Boolean
            + enleverCarteJoueur(index : Integer) : Boolean
            + getCartesEnMain() : ArrayList<Animal>
            + genererPioche() : String
            + getPosition(c : Carte) : Integer
            + creeMain() : String
            + aPlace() : Boolean
            + aPlaceCarte(index : Integer) : Boolean
            + placerObst() : Boolean
            + getCarteJoueur(place : Integer)
            + getSangJoueur() : Integer
            + getCartesLigenBas() : ArrayList<Carte>
            + getCartesLigneBas(index : Integer) : Carte
            + verifierMorts()
            + clear()
            + appliquerPouvoir(source : Animal, cible : Carte)
        }
        class Adversaire {
            - m_actionsPlanifiees : Carte[*]
            - m_listeE : ArrayList<Carte>
            - m_ligneEPT : ArrayList<Carte>
            - m_pouvoir : ArrayList<Pouvoir>
            - m_nbObsE  = 0 : Integer
            + <<create>> Adversaire()
            + placerCarteEnnemi(c : Carte, pos : integer)
            + setCarteIntention(c : Carte, pos : Integer)
            + avancerLigne() : Boolean
            + clear()
            + addCarte(ani : Animal)
            + getCarteEnnemi(place : Integer)
            + getCartesIntentions() : ArrayList<Carte>
            + getCartesLigneHaut() : ArrayList<Carte>
            + planifierProchainTour()
            + envoyerIntentionsAuPlateau()
            + aPlace(index : Integer) : Boolean
            + changerSlot(c : Carte, pos : Integer) : String
            + getPosition(c : Carte) : Integer
            + appliquerPouvoir(source : Animal, cible : Carte) : String
            + placerObst() : Boolean
            + verifierMorts()
            + estCaseLibre(pos : Integer)
        }
    }

    package model {
        abstract class Carte <<abstract>> {
            - m_nom : String
            - m_pointsVie = 0 : Integer
            - m_vieInit = 0 : Integer
            - m_Attack  = 0 : Integer
            + <<create>> Carte(m : String, num : Integer, type : String)
            + <<create>> Carte(m : String, num : Integer, type : String, degat : Integer)
            + getInitVie() : Integer
            + getNom() : String
            + getVie() : Integer
            + modifierNom(n : String) : String
            + modifierVie(changement : Integer) : String
            + ajouterVie(changement : Integer) : String
            + setPouvoir(p : Pouvoir)
            + estAnimal() : Boolean
            + getVolant() : Boolean
            + getPouvoir() : Pouvoir
            + ajouterAttack(i : Integer)
            + getAttack() : Integer
            + estVie() : Boolean
            + toString() : String
        }

        class Animal extends Carte {
            - m_pointsAttaque : Integer
            - m_coutSang : Integer
            - m_coutOs : Integer
            - m_volant : Boolean
            - m_pouvoir = null : Pouvoir
            + <<create>> Animal(ani : Animal)
            + <<create>> Animal(nom : String, pv : Integer, pointsAttaque : Integer, sang : Integer, os : Integer, volant : Boolean)
            + <<create>> Animal(nom : String, pv : Integer, pointsAttaque : Integer, sang : Integer, os : Integer, volant : Boolean, p : Pouvoir)
            + getAttack() : Integer
            + getCoutSang() : Integer
            + getCoutOs() : Integer
            + ajouterCoutSang(i : Integer) : String
            + setPouvoir(p : Pouvoir) : String
            + estAnimal() : Boolean
            + getVolant() : Boolean
            + getPouvoir() : Pouvoir
            + ajouterAttack(i : Integer)

        }

        class Obstacle extends Carte {
            + <<create>> Obstacle(nom : String, pv : Integer)
            + setPouvoir(p : Pouvoir) : String
            + estAnimal() : Boolean
            + getVolant() : Boolean
            + getPouvoir() : Pouvoir
            + ajouterAttack(i : Integer)
            + getAttack() : Integer
        }
        class Pouvoir{
            - m_type : String
            - m_nom : String
            - m_activeDans = 0 : Integer
            + <<create>> Pouvoir(nom : String, type : String, active : Integer)
            + getActive() : Integer
            + modifActive(i : Integer) : String
            + getType() : String
        }
    }

    package view {
        class AffichageConsole {
            - m_LARGEUR_CARTE = 16 : Integer
            - m_HAUTEUR_CARTE = 11 : Integer
            - m_screen : Screen
            - m_graphics : TextGraphics
            - m_largeurEcran : Integer
            - m_hauteurEcran : Integer
            - m_decalageDynamique : Integer
            - m_margeGauche : Integer
            - m_ligneBoiteSaisie : Integer
            - m_historiqueLogs = new ArrayList<> : ArrayList<String>
            + initEcran() : Boolean
            + mettreAJourDimensions()
            + getColDep(coor : Integer)
            + ajouterLog(message : String)
            + dessinerCarteLogs(ligneDebut)
            + dessinerJeuSansPlateau(cartesterrainJoueur : ArrayList<Carte>, intentionsAdversaire : ArrayList<Carte>, cartesterrainAdversaire : ArrayList<Carte>, joueur : jeu.logic.joueur, score : Integer, numPartie : Integer, victoireJ : Integer, victoireE : Integer)
            + updatePioche(coor : Integer, ligne : Integer, joueur : Joueur)
            + afficherMessageAlerte(message : String)
            + afficherChoix() : String
            + dessineCarte(c : Carte, ligneDep : Integer, coor : Integer) : Boolean
            + dessinerCarteVide(label : String, ligneDebut : Integer, coordonnee : Integer)
            + rafraichir()
            + effacer()
            + afficherFin(entiteGagnante : Object, estFinpartieTotale : Boolean)
        }
    }
}

' --- Relations et Dépendances ---
Main .> GestionPartie : <<call>>
Carte *--> Joueur : m_ligenJ <
Carte *--> Adversaire : m_listeE <
GestionPartie *--> Joueur : m_j <
GestionPartie *--> Adversaire : m_adv <
GestionPartie *--> Pouvoir : m_pouv <
GestionPartie ..> Combat : <<use>>
GestionPartie ..> Score : <<use>>
GestionPartie ..> AffichageConsole : <<use>>

@enduml
